# -*- coding: utf-8 -*-
"""ImageDetection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wYDshbcTMrW2v1rw_8-IHB0vIHwNYaTm
"""

import cv2

import matplotlib.pyplot as plt

img1= plt.imread("70D.jpg")

plt.imshow(img1)

classifier=cv2.CascadeClassifier("haarcascade_frontalface_default.xml")

gray_img1 = cv2.cvtColor(img1, cv2.COLOR_RGB2GRAY)

rectangles=classifier.detectMultiScale(gray_img1)

len(rectangles)

i=0
while i<len(rectangles):
  cv2.rectangle(img1,(rectangles[i][0],rectangles[i][1]),(rectangles[i][0]+rectangles[i][2],rectangles[i][1]+rectangles[i][3]),(255,0,0),10)
  i+=1

plt.imshow(img1)